version: '3.1'

services:
  uService_pg:
    image: postgres:15.1
    container_name: uService_pg
    restart: always
    environment:
      POSTGRES_DB: marseniusers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: huevos2099
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432
